# **Laboratorio N°5: Número de Condición**


In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Ejercicio 1

En este ejercicio vamos a probar o refutar algunas propiedades sobre el numero de condicion.
En cada item tendremos un propiedad que puede ser verdadera o falsa.
 - En caso de ser verdadera: dar su demostracion.
 - En caso de ser falsa: utilizar numpy para dar un contraejemplo.

Utilizar el comando `np.linalg.cond`.

**(a)** $Cond_2(A)$ + $Cond_2(B)$ = $Cond_2(A+B)$

In [9]:
def generate_random_invertible_matrix(size):
    while True:
        matrix = np.random.randn(size, size)
        

        if np.linalg.det(matrix) != 0:
            return matrix

# Example usage
size = 3 
matrix = generate_random_invertible_matrix(size)

print(matrix)

matrix2 = generate_random_invertible_matrix(size)

print(matrix2)


print(np.linalg.cond(matrix,p=2)+np.linalg.cond(matrix2,p=2) == np.linalg.cond(matrix+matrix2,p=2))

#ES FAKE!

[[ 0.45657828  2.25466313 -0.51005042]
 [-1.44306431  0.50719238 -0.1467983 ]
 [ 0.13481334 -0.81265664 -0.13881559]]
[[-0.76481071  1.33974196 -0.96991781]
 [-0.80859808  0.43498471 -0.04129035]
 [-0.54281464  0.85921337 -0.68409616]]
False


**(b)** $Cond_1(A)$ - $Cond_1(B)$ = $Cond_2(A-B)$

In [13]:
size = 3  
matrix = generate_random_invertible_matrix(size)

print(matrix)

matrix2 = generate_random_invertible_matrix(size)

print(matrix2)


print(np.linalg.cond(matrix,p=1)+np.linalg.cond(matrix2,p=1) == np.linalg.cond(matrix+matrix2,p=1))

#ES FAKE!

[[ 0.41346466 -0.14360368  1.49307868]
 [ 0.92024437 -0.31768963 -0.52400243]
 [-1.0419042   0.67714764  0.78433784]]
[[-1.01321389  0.18288241 -0.58276616]
 [ 0.60740193  0.13322584  0.13535947]
 [ 0.56192193  1.15379099 -0.64772002]]
False


**(c)** $Cond_2(A)$ * $Cond_2(B)$ = $Cond_2(A.B)$

In [17]:
size = 3  
matrix = generate_random_invertible_matrix(size)

print(matrix)

matrix2 = generate_random_invertible_matrix(size)

print(matrix2)


print(np.linalg.cond(matrix,p=1)*np.linalg.cond(matrix2,p=1) == np.linalg.cond(matrix@matrix2,p=1))

#ES FAKE!

[[-0.09536235  0.06638418  0.28861466]
 [ 0.45928959  1.52720386 -0.78376987]
 [-0.17581065 -1.02476697 -1.17010338]]
[[-2.54168648 -1.01020249 -0.65192294]
 [-0.57964797  0.4778218   2.36138554]
 [ 0.15033087 -1.31070705  1.35399221]]
False


## Ejercicio 2

El objetivo de este ejercicio es estudiar el número de condición de
algunas matrices a medida que su tamaño aumenta.



**(a)** Programar funciones que, dado $n \in \mathbb{N}$, devuelvan las siguientes matrices de $\mathbb{R}^{n\times n}$. La función que define $B_n$ ya viene dada.


\begin{equation*}
A_n=
\begin{pmatrix}
\frac{1}{n} & 0 & 0 & \cdots  & n^2\\
0 & \frac{1}{n} & 0 & \cdots & 0 \\
0 & 0 & \frac{1}{n} & \cdots & 0\\
\vdots & \vdots & \vdots  & \ddots & \vdots\\
1 & 0 & 0 & \cdots &  \frac{1}{n}\\
\end{pmatrix}
\qquad
B_n=
\begin{pmatrix}
4 & 1 & 0 & \cdots & 0 & 0\\
1 & 4 & 1 & \cdots & 0 & 0 \\
0 & 1 & 4 & \ddots &  & \vdots\\
\vdots & \vdots & \ddots & \ddots & \ddots & \vdots \\
0 & 0 &  & \ddots & 4 & 1\\
0 & 0 & \cdots & \cdots & 1 & 4 \\
\end{pmatrix}
\qquad
H_n=
\begin{pmatrix}
1 & \frac{1}{2} & \frac{1}{3} & \cdots  & \frac{1}{n}\\
\frac{1}{2} & \frac{1}{3} & \frac{1}{4} & \cdots & \frac{1}{n+1} \\
\frac{1}{3} & \frac{1}{4} & \frac{1}{5} & \cdots & \frac{1}{n+2}\\
\vdots & \vdots & \vdots  & \ddots & \vdots\\
\frac{1}{n} & \frac{1}{n+1} & \frac{1}{n+2} & \cdots &  \frac{1}{2n-1}\\
\end{pmatrix}
\end{equation*}



**Sugerencia:** Utilizar la función `np.diag` que recibe un array de números y genera una matriz diagonal con elementos dados por el array.




In [24]:
def matriz_B(n):
  B = np.eye(n, k=-1) + 4*np.eye(n, k=0) + np.eye(n, k=1)
  return B

mattrizprueba = np.eye(5,k=-5+1)
print(mattrizprueba)

def matriz_A(n):
    
    A= np.eye(n,k=0)/n + np.eye(n,k=n-1)*n*n + np.eye(n,k=-n+1)

def secuencia(n):
    for i in range(1,n):
        print((1/(2*i-1)))

secuencia(5)


def matriz_H(n):
    pass
    

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
1.0
0.3333333333333333
0.2
0.14285714285714285


**(b)** Graficar para 100 vectores **unitarios** (en norma 2), $v\in\mathbb{R^2}$, $\; A_2v,\ B_2v,\ H_2v$

In [ ]:
B = matriz_B(2)
V = np.random.rand(2, 100) - 0.5
V = #COMPLETAR
BV = # COMPLETAR

plt.scatter(V[0], V[1], label = "v")
plt.scatter(BV[0], BV[1], label = "Bv")
plt.legend()


**(c)** Programar una función que, dada una matriz $M_n$ y un número natural $N$, guarde en un vector el valor de $Cond_2(M_n)$ para $1\leq n \leq N$.

In [ ]:
def vector_condicion(M, N):
  #COMPLETAR
  #...
  return()

**(d)** Realizar gráficos del número de condición en norma 2 de las matrices definidas arriba para $N=10$.


In [ ]:
x= #COMPLETAR
y= #COMPLETAR

plt.plot(x, y)
plt.show()

**Sugerencia:** Si es necesario, utilizar una escala logarítmica en el eje $y$.

**(e)** Repetir el ítem (d) para la matriz de Hilbert con $N=50$. ¿Cómo se explica el comportamiento observado?

In [ ]:
#COMPLETAR

## Ejercicio 3 (Ej 20 - Práctica 2)

Sea
$A=\left(
\begin{array}{ccc}
3&0 & 0\\
0& \frac 54 & \frac 34\\
0& \frac 34 & \frac 54\\
\end{array}
\right).$



In [ ]:
A = np.array([[3.0, 0, 0], [0, 5/4, 3/4], [0, 3/4, 5/4]])

(a) Calcular $Cond_\infty(A)$.


In [ ]:
#COMPLETAR

(b) ¿Cuán chico debe ser el error relativo en los datos, $\frac{\|b-\tilde{b}\|}{\|b\|}$, si se desea que el error relativo en la aproximación de la solución, $\frac{\|x-\tilde{x}\|}{\|x\|}, $ sea menor que $10^{-4}$ (en $\|\cdot\|_{\infty}$)?



In [ ]:
#COMPLETAR

(c) Realizar experimentos numéricos para verificar las estimaciones del ítem anterior. Considerar $b=(3,2,2)^t$, que se corresponde con la solución exacta $x=(1,1,1)^t$. Generar vectores de error aleatorios, normalizarlos para que su norma sea tan chica como la estimada en el item anterior y perturbar $b$ obteniendo $\tilde{b}$. Finalmente, resolver $A\tilde{x}=\tilde{b}$ y verificar que $\|\tilde{x}-x\|<10^{-4}$.

In [ ]:
#COMPLETAR