### Consigna 

1. **Inversión de Matrices:**
   Completar la función `invertir_matriz(A)` para calcular la **inversa** de la matriz \( A \) utilizando **eliminación gaussiana** y sustitución hacia atrás. 

2. **Sistema de Ecuaciones Lineales:**
   Completar la función `resolver_sistema(A, b)` para resolver el sistema lineal \( A \mathbf{x} = \mathbf{b} \). Utilizar la función `invertir_matriz(A)`.

3. **Cambio de Base:**
   Completar la función `cambio_base_matriz(B_prime, B)` para calcular la matriz de **cambio de base** de \( B \) a \( B' \).


In [15]:
import numpy as np

def escalonar_filas(M):
    """ 
        Retorna la Matriz Escalonada por Filas 
    """
    A = np.copy(M)
    if (issubclass(A.dtype.type, np.integer)):
        A = A.astype(float)

    # Si A no tiene filas o columnas, ya esta escalonada
    f, c = A.shape
    if f == 0 or c == 0:
        return A

    # buscamos primer elemento no nulo de la primera columna
    i = 0
    
    while i < f and A[i,0] == 0:
        i += 1

    if i == f:
        # si todos los elementos de la primera columna son ceros
        # escalonamos filas desde la segunda columna
        B = escalonar_filas(A[:,1:])
        
        # y volvemos a agregar la primera columna de zeros
        return np.block([A[:,:1], B])


    # intercambiamos filas i <-> 0, pues el primer cero aparece en la fila i
    if i > 0:
        A[[0,i],:] = A[[i,0],:]

    # PASO DE TRIANGULACION GAUSSIANA:
    # a las filas subsiguientes les restamos un multiplo de la primera
    A[1:,:] -= (A[0,:] / A[0,0]) * A[1:,0:1]

    # escalonamos desde la segunda fila y segunda columna en adelante
    B = escalonar_filas(A[1:,1:])

    # reconstruimos la matriz por bloques adosando a B la primera fila 
    # y la primera columna (de ceros)
    return np.block([ [A[:1,:]], [ A[1:,:1], B] ])


def back_substitution(A_aug):
    """
    Realiza la sustitución hacia atrás para obtener la identidad en el lado izquierdo
    de la matriz aumentada y la inversa en el lado derecho.
    """
    n = A_aug.shape[0]
    
    # Desde la última fila hacia la primera
    for i in range(n-1, -1, -1):
        # Normalizar la fila de pivote
        A_aug[i] = A_aug[i] / A_aug[i, i]
        
        # Hacer ceros en las filas superiores
        for j in range(i):
            A_aug[j] -= A_aug[i] * A_aug[j, i]
    
    return A_aug[:, n:]

matiz=np.array([[2.0,2.0],[0.0,1.0]])

print(matiz)
id=np.eye(2)






[[2. 2.]
 [0. 1.]]
[[2. 2.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]


array([[2., 2., 1., 0.],
       [0., 1., 0., 1.]])

In [25]:
def invertir_matriz(A):
    """
    Calcula la inversa de la matriz A utilizando eliminación gaussiana.
    """
    tamaño=np.shape(A)

    A_aumentada = np.c_[A,np.eye(tamaño[0])]
    
    escalonar_filas(A_aumentada)

    A_inv=back_substitution(A_aumentada)
    
    # Crear una matriz aumentada con A y la identidad, aplicamos eliminacion y la sustitución hacia atrás.

    #hasta aca, A aumentada es la matriz inversa, pero tengo q elegir ahora la mitad. eso es haciedno fias sobre 2
    
    

    

    
    return A_inv

res=invertir_matriz(matiz)

print(res)

def resolver_sistema(A, b):
    pass
    """
    Resuelve el sistema Ax = b utilizando la inversa de A obtenida mediante eliminación gaussiana.
    """

    A_inv = invertir_matriz(A)
    x = A_inv @ b
    return x




# Modificación de la función de cambio de base
def cambio_base_matriz(B_prime, B):
    pass
    """
    Calcula la matriz de cambio de base de B a B' usando `resolver_sistema`.
    """
    n = len(B)
    C = np.zeros((n, n))
    
    # Resolver los sistemas B_prime_i = C * B_i

    #necesito la inversa de B´.
    """
    BprimaInv = invertir_matriz(B_prime)

    Cbb= BprimaInv @ B

    Esto es una forma

    """
    for i in range(n):
        C[:, i] = resolver_sistema(B_prime.T,B[i])
    
    
    return Cbb


[[ 0.5 -1. ]
 [ 0.   1. ]]


### Ayuda. Cambios de Base.

Dadas dos bases $ B = \{\mathbf{v}_1, \mathbf{v}_2, \dots, \mathbf{v}_n\} $ y $ B' = \{\mathbf{w}_1, \mathbf{w}_2, \dots, \mathbf{w}_n\} $, queremos encontrar la **matriz de cambio de base** $ C $, que permite expresar un vector en la base $ B $ como combinación lineal de los vectores de la base $ B' $.

La matriz de cambio de base $ C $ debe satisfacer:
$$
[\mathbf{x}]_B = C [\mathbf{x}]_{B'}
$$
Es decir, el vector $ \mathbf{x} $ en la base $ B' $ se puede transformar a la base $ B $ multiplicando por la matriz $ C $.

Para obtener $ C $, necesitamos expresar cada vector de $ B' $, $ \mathbf{w}_i $, como combinación lineal de los vectores de $ B $, es decir, encontrar los coeficientes $ c_{ij} $ tales que:
$$
\mathbf{w}_i = c_{i1} \mathbf{v}_1 + c_{i2} \mathbf{v}_2 + \dots + c_{in} \mathbf{v}_n
$$
Esto se puede expresar de forma matricial como:
$$
\mathbf{w}_i = C_i \mathbf{v}
$$
Donde:
- $ \mathbf{w}_i $ es el $ i $-ésimo vector de la base $ B' $,
- $ C_i $ es el $ i $-ésimo vector columna de la matriz de cambio de base $ C $,
- $ \mathbf{v} $ es el vector de la base $ B $ con los vectores $ \mathbf{v}_1, \mathbf{v}_2, \dots, \mathbf{v}_n $.

Entonces, para hallar C:

1. Para cada vector $ \mathbf{w}_i \in B' $, resolvemos el sistema $ B \cdot C_i = \mathbf{w}_i $.
2. Los coeficientes $ C_i $ formarán las columnas de la matriz de cambio de base $ C $.
3. Esto lo hacemos utilizando un algoritmo de resolución de sistemas lineales (sin `np.linalg.solve`, usando eliminación gaussiana, por ejemplo).

El bucle del código:
```
for i in range(n):
    C[:, i] = ...
```

Resuelve el sistema para cada vector $ \mathbf{w}_i \in B' $ y almacena los coeficientes en las columnas de la matriz $ C $.